@startuml webserv_class

!theme blueprint

skinparam IconPrivate {
  Color #FF0000

  BackgroundColor #FF0000
}
skinparam IconPublic {
  Color #00FF00
  BackgroundColor #00FF00
}
skinparam IconProtected {
  Color #ff7f00
  BackgroundColor #ff7f00
}

!include ../../libs/common/doc/puml/class.puml
!include ../../libs/logger/doc/puml/class.puml
!include ../../libs/parser/doc/puml/class.puml

title Class Diagram for Webserv 

namespace webserv.HTTPheaders {

	class "HTTPHeader" as HTTPHeader {
		- _logger : t_Logger
		- _name : string
		- _value : string
		- _description : string
		--
		+ HTTPHeader(name : string, description : string)
		+ HTTPHeader(name : string, value : string, description : string)
		+ {static} getLogger() : t_Logger
		+ getName() : string
		+ getValue() : string
		+ setValue(value : string) : void
		+ getDescription() : string
	}

	class "HTTPHeadersRegistry" as HTTPHeadersRegistry <<singleton>> {
		- _logger : t_Logger
		- _headers : t_HeadersRegistry
		--
		- HTTPHeadersRegistry()
		+ getLogger() : t_Logger
  		+ {static} getInstance() : HTTPHeadersRegistry
		+ getHeader(name : string) : HTTPHeader
	}
}

namespace webserv.status {

	class "StatusCode" as StatusCode {
		- _logger : t_Logger
		- _code : unsigned short
		- _msg : string
		- _description : string
		--
		+ StatusCode()
		+ StatusCode(code : unsigned short, msg : string, description : string)
		+ {static} getLogger() : t_Logger
		+ getCode() : int
		+ getMessage() : string
		+ getDescription() : string
	}

	class "StatusCodeRegistry" as StatusCodeRegistry <<singleton>> {
		- _logger : t_Logger
		- _statusCodes : t_StatusCodesRegistry
		--
		- StatusCodeRegistry()
		+ getLogger() : t_Logger
  		+ {static} getInstance() : StatusCodeRegistry
		+ getStatusCode(code : unsigned short) : StatusCode
	}
}

namespace webserv.client {

	enum "e_RequestFlags" as e_RequestFlags {
		E_REQ_REQUEST_LINE = 1 << 0
		E_REQ_HEADERS_VALIDATED = 1 << 1
		E_REQ_BODY_STARTED = 1 << 2
	}

	class "Request" as Request  {
		- _logger : t_Logger
		- _method : e_Method
		- _locationConfig : LocationConfig
		- _requestTarget : string
		- _httpVersion : string
		- _absolutePath : string
		- _authority : string
		- _path : string
		- _query : string
		- _headers : t_Headers
		- _flags : e_RequestFlags
		--
		+ Request()
		+ {static} getLogger() : t_Logger
		+ getMethod() : e_Method
		+ setMethod(method : e_Method) : void
		+ getRequestTarget() : string
		+ setRequestTarget(requestTarget : string) : void
		+ getHttpVersion() : string
		+ setHttpVersion(httpVersion : string) : void
		+ getAbsolutePath() : string
		+ setAbsolutePath(absolutePath : string) : void
		+ getAuthority() : string
		+ setAuthority(authority : string) : void
		+ getPath() : string
		+ setPath(path : string) : void
		+ getQuery() : string
		+ setQuery(query : string) : void
		+ getHeaders() : t_Headers
		+ setHeaders(headers : t_Headers) : void
		+ findHeader(headerName : string, headerValue : string) : HTTPHeader
		+ addHeader(headerName : string, headerValue : string) : void
		+ getFlags() : e_RequestFlags
		+ setFlags(flags : e_RequestFlags) : void
		+ getLocationConfig() : LocationConfig
		+ setLocationConfig(locationConfig : LocationConfig) : void
	}

	enum "e_ResponseFlags" as e_ResponseFlags {
		E_RESP_HEADERS_SENT = 1 << 0
	}

	class "Response" as Response {
		- _logger : t_Logger
		- _httpVersion : string
		- _statusCode : StatusCode
		- _headers : t_Headers
		- _flags : e_ResponseFlags
		- _shouldCloseConnection : bool
		--
		+ Response()
		+ {static} getLogger() : t_Logger
		+ getHttpVersion() : string
		+ setHttpVersion(httpVersion : string) : void
		+ getStatusCode() : StatusCode
		+ setStatusCode(statusCode : StatusCode) : void
		+ getHeaders() : t_Headers
		+ setHeaders(headers : t_Headers) : void
		+ findHeader(headerName : string, headerValue : string) : HTTPHeader
		+ addHeader(headerName : string, headerValue : string) : void
		+ getFlags() : e_ResponseFlags
		+ setFlags(flags : e_ResponseFlags) : void
		+ shouldCloseConnection() : bool
		+ setShouldCloseConnection(shouldCloseConnection : bool) : void

	}

	class "HTTPError" as HTTPError <<exception>> {
		- _logger : t_Logger
		- _statusCode : StatusCode
		- _what : string
		- _location : string
		--
		+ HTTPError(code : int)
		+ HTTPError(code : int, location : string)
		+ {static} getLogger() : t_Logger
		+ getStatusCode() : StatusCode
		+ setStatusCode(statusCode : StatusCode) : void
		+ getLocation() : string
		+ what() : string
	}

	enum "e_ClientStatus" as e_ClientStatus {
		E_CLI_REQUEST
		E_CLI_ERR_PARSING
		E_CLI_DISCONNECTED
	}

	class "Client" as Client {
		- _logger : t_Logger
		- _id : int
		- _socket : common::core::net::TcpClient
		- _sockaddr_storage : sockaddr_storage
		- _status : e_ClientStatus
		- _serverConfig : ServerConfig
		- _executionHandler : ExecutionHandler
		- _requestHandler : RequestHandler
		- _responseHandler : ResponseHandler
		- _HTTPError : HTTPError
		- _lastActivityTime : time_t
		- _effectiveKeepaliveTimeout : time_t
		--
		+ Client(client : t_SocketPairClient, serverConfig : ServerConfig)
		+ {static} getLogger() : t_Logger
		+ getSocket() : common::core::net::TcpClient
		+ setSocket(socket : common::core::net::TcpClient) : void
		+ getSockaddrStorage() : sockaddr_storage
		+ setSockaddrStorage(sockaddr_storage : sockaddr_storage) : void
		+ getStatus() : e_ClientStatus
		+ setStatus(status : e_ClientStatus) : void
		+ getExecutionHandler() : ExecutionHandler
		+ getRequestHandler() : RequestHandler
		+ getResponseHandler() : ResponseHandler
		+ getServerConfig() : ServerConfig
		+ getHTTPError() : HTTPError
		+ setHTTPError(error : HTTPError) : void
		+ getLastActivityTime() : time_t
		+ setLastActivityTime(time : time_t) : void
		+ getEffectiveKeepaliveTimeout() : time_t
		+ setEffectiveKeepaliveTimeout(timeout : time_t) : void
		+ receiveData() : void
		+ sendData() : void
		+ processHTTPCycle() : void
		+ buildErrorResponse() : void
		+ resetAll() : void
	}
}

namespace webserv.handler {

	class "ClientHandler" as ClientHandler {
		- _logger : t_Logger
		- _clients : t_Clients
		- _ioMultiplexer : t_ioMultiplexer
		--
		+ ClientHandler()
		+ {static} getLogger() : t_Logger
		+ setIoMultiplexer(ioMultiplexer : t_ioMultiplexer) : void
		+ addClient(client : t_SocketPairClient, serverConfig : ServerConfig) : void
		+ removeClient(client : Client) : t_Clients::iterator
		+ processClients() : void
	}

	class "RequestHandler" as RequestHandler {
		- _logger : t_Logger
		- _request : Request
		- _bufferRequest : t_raw
		- _parser : Parser
		- _serverConfig : ServerConfig
		--
		- validateHeaders() : void
		- buildAbsolutPath() : void
		- normalizePath(path : string) : string
		+ RequestHandler(serverConfig : ServerConfig)
		+ {static} getLogger() : t_Logger
		+ parseHeaders() : void
		+ parseBody() : void
		+ getRequest() : Request
		+ setRequest(request : Request) : void
		+ getBufferRequest() : t_raw
		+ appendToBufferRequest(buffer : t_raw) : void
		+ eraseBufferRequestFront(n : size_t) : void
		+ clearBufferRequest() : void
		+ getParser() : Parser
	}

	class "ResponseHandler" as ResponseHandler {
		- _logger : t_Logger
		- _response : Response
		- _bufferResponse : t_raw
		--
		- buildStatusLine(httpVersion : string, statusCode : StatusCode, reasonPhrase : string) : void
		- buildHeaders(request : Request, parseFlags : int) : void
		+ ResponseHandler()
		+ {static} getLogger() : t_Logger
		+ getResponse() : Response
		+ setResponse(response : Response) : void
		+ appendToBufferResponse(buffer : t_raw) : void
		+ clearBufferResponse() : void
		+ getBufferResponse() : t_raw
		+ eraseBufferResponseFront(n : size_t) : void
		+ buildHeadersResponse(request : Request, execFlags : int, parseFlags : int) : void
		+ buildErrorResponse(request : Request, error : HTTPError) : void
	}

	enum "e_ExecutionHandlerFlags" as e_ExecutionHandlerFlags {
		E_EXEC_FILE_OPENED = 1 << 0
		E_EXEC_COMPLETE = 1 << 1
		E_EXEC_CREATED = 1 << 2
		E_EXEC_NOCONTENT = 1 << 3
	}

	class "ExecutionHandler" as ExecutionHandler {
		- _logger : t_Logger
		- _fd : common::core::raii::UniqueFd
		- _bodyReceived : ssize_t
		- _flags : e_ExecutionHandlerFlags
		- _autoindexBuffer : t_raw
		--
		- executeHEADorGET(requestHandler : RequestHandler, responseHandler : ResponseHandler, locationConfig : LocationConfig) : void
		- executePOST(requestHandler : RequestHandler, locationConfig : LocationConfig) : void
		- executePUT(requestHandler : RequestHandler, locationConfig : LocationConfig) : void
		- executeDELETE(requestHandler : RequestHandler, locationConfig : LocationConfig) : void
		- openFile(requestHandler : RequestHandler, locationConfig : LocationConfig) : void
		- readChunk(responseHandler : ResponseHandler) : void
		- writeChunk(requestHandler : RequestHandler) : void
		- getFileSize(path : string) : int
		- getFileExtension(path : string) : string
		- isFile(path : string) : bool
		- isExisting(path : string) : bool
		- deleteFile(filePath : string) : void
		- deleteDirectory(dirPath : string) : void
		- isDirectory(path : string) : bool
		- generateAutoindexHTML(dirPath : string) : string

		+ ExecutionHandler()
		+ {static} getLogger() : t_Logger
		+ getFd() : int
		+ getBodyReceived() : size_t
		+ setBodyReceived(bodyReceived : size_t) : void
		+ getFlags() : int
		+ setFlags(flags : int) : void
		+ getAutoindexBuffer(buffer : t_raw) : t_raw
		+ setAutoindexBuffer(buffer : t_raw) : void
		+ execute(requestHandler : RequestHandler, responseHandler : ResponseHandler, locationConfig : LocationConfig) : void
		+ executeCGI(requestHandler : RequestHandler, locationConfig : LocationConfig) : void
		+ executeRequest(requestHandler : RequestHandler, responseHandler : ResponseHandler, locationConfig : LocationConfig) : void
	}
}

namespace webserv.parser {

	enum "e_ParserFlags" as e_ParserFlags {
		E_PARS_HOST = 1 << 0
		E_PARS_CONNECTION = 1 << 1
		E_PARS_CONTENT_LENGTH = 1 << 2
		E_PARS_CONTENT_TYPE = 1 << 3
		E_PARS_CONTENT_ENCODING = 1 << 4
		E_PARS_EXPECT = 1 << 5
		E_PARS_CLRF = 1 << 6
	}

	class "Parser" as Parser {
		- _logger : t_Logger
		- {static} _abnf : abnf::Abnf
		- {static} _config : HTTPConfig
		- _flags : e_ParserFlags
		- _buffer : t_raw
		--
		+ Parser()
		+ {static} getLogger() : t_Logger
		+ getFlags() : int
		+ setFlags(flags : int) : void
		+ parseConfig(buffer : t_raw) : void
		+ parseRequestLine(line : string, request : Request) : void
		+ parseHeaders(headersBlock : string, request : Request) : void
	}
}

namespace webserv.config {

	enum "e_Method" as e_Method {
		GET
		HEAD
		POST
		PUT
		DELETE
	}

	enum "e_Modifier" as e_Modifier {
		PREFIX
		EXACT
		PREFIX_PRIORITY
	}

	class "Listen" as Listen <<struct>> {
		+ address : string
		+ port : string
		+ defaultServer : bool
		+ backlog : int
		+ rcvbuf : int
		+ sndbuf : int
		+ ipv6only : bool
		+ reuseport : bool
		+ so_keepalive : bool
	}

	class "Return" as Return <<struct>> {
		+ statusCode : StatusCode
		+ url : string
	}

	class "ErrorPage" as ErrorPage {
		- _logger : t_Logger
		- _codes : t_StatusCodes
		- _path : string
		--
		+ ErrorPage(codes : t_StatusCodes, path : string)
		+ {static} getLogger() : t_Logger
		+ getCodes() : t_StatusCodes
		+ getPath() : string
	}

	class "HTTPConfig" as HTTPConfig <<singleton>> {
		- _logger : t_Logger
		- _ioMultiplexer : string
		- _clientMaxBodySize : t_clientMaxBodySize
		- _davPutPath : string
		- _davAccess : t_Perms
		- _davMethods : t_DavMethods
		- _defaultType : string
		- _errorPage : t_ErrorPages
		- _keepAliveTimeout : t_keepAliveTimeout
		- _root : string
		- _serverConfigs : t_ServerConfigs
		- _types : t_MimeTypes
		- _enableCGI : bool
		- _cgiExtensions : t_CgiExtensions
		--
		- HTTPConfig()
		+ {static} getLogger() : t_Logger
		+ {static} getInstance() : HTTPConfig
		+ getIOMultiplexer() : string
		+ setIOMultiplexer(ioMultiplexer : string) : void
		+ getClientMaxBodySize() : t_clientMaxBodySize
		+ setClientMaxBodySize(clientMaxBodySize : t_clientMaxBodySize) : void
		+ getDavPutPath() : string
		+ setDavPutPath(davPutPath : string) : void
		+ getDavAccess() : t_Perms
		+ setDavAccess(davAccess : t_Perms) : void
		+ getDavMethods() : t_DavMethods
		+ setDavMethods(davMethods : t_DavMethods) : void
		+ getDefaultType() : string
		+ setDefaultType(defaultType : string) : void
		+ getErrorPage() : t_ErrorPages
		+ setErrorPage(errorPage : t_ErrorPages) : void
		+ getKeepAliveTimeout() : t_keepAliveTimeout
		+ setKeepAliveTimeout(keepAliveTimeout : t_keepAliveTimeout) : void
		+ getRoot() : string
		+ setRoot(root : string) : void
		+ getServerConfigs() : t_ServerConfigs
		+ setServerConfigs(serverConfigs : t_ServerConfigs) : void
		+ getTypes() : t_MimeTypes
		+ setTypes(types : t_MimeTypes) : void
		+ getEnableCGI() : bool
		+ setEnableCGI(enableCGI : bool) : void
		+ getCgiExtensions() : t_CgiExtensions
		+ setCgiExtensions(cgiExtensions : t_CgiExtensions) : void
	}

	class "ServerConfig" as ServerConfig {
		- _logger : t_Logger
		- _clientMaxBodySize : t_clientMaxBodySize
		- _davPutPath : string
		- _davAccess : t_Perms
		- _davMethods : t_DavMethods
		- _defaultType : string
		- _errorPage : t_ErrorPages
		- _keepAliveTimeout : t_keepAliveTimeout
		- _listen : t_Listen
		- _locationConfigs : t_LocationConfigs
		- _root : string
		- _serverName : t_Servernames
		- _types : t_MimeTypes
		- _enableCGI : bool
		- _cgiExtensions : t_CgiExtensions
		--
		+ ServerConfig()
		+ {static} getLogger() : t_Logger
		+ getClientMaxBodySize() : t_clientMaxBodySize
		+ setClientMaxBodySize(clientMaxBodySize : t_clientMaxBodySize) : void
		+ getDavPutPath() : string
		+ setDavPutPath(davPutPath : string) : void
		+ getDavAccess() : t_Perms
		+ setDavAccess(davAccess : t_Perms) : void
		+ getDavMethods() : t_DavMethods
		+ setDavMethods(davMethods : t_DavMethods) : void
		+ getDefaultType() : string
		+ setDefaultType(defaultType : string) : void
		+ getErrorPage() : t_ErrorPages
		+ setErrorPage(errorPage : t_ErrorPages) : void
		+ getKeepAliveTimeout() : t_keepAliveTimeout
		+ setKeepAliveTimeout(keepAliveTimeout : t_keepAliveTimeout) : void
		+ getListen() : t_Listen
		+ setListen(listen : t_Listen) : void
		+ getLocationConfigs() : t_LocationConfigs
		+ setLocationConfigs(locationConfigs : t_LocationConfigs) : void
		+ getRoot() : string
		+ setRoot(root : string) : void
		+ getServerNames() : t_Servernames
		+ setServerNames(serverNames : t_Servernames) : void
		+ getTypes() : t_MimeTypes
		+ setTypes(types : t_MimeTypes) : void
		+ getEnableCGI() : bool
		+ setEnableCGI(enableCGI : bool) : void
		+ getCgiExtensions() : t_CgiExtensions
		+ setCgiExtensions(cgiExtensions : t_CgiExtensions) : void
		+ findLocationConfig(path : string) : LocationConfig
	}

	class "LocationConfig" as LocationConfig {
		- _logger : t_Logger
		- _autoindex : bool
		- _clientMaxBodySize : t_clientMaxBodySize
		- _davPutPath : string
		- _davAccess : t_Perms
		- _davMethods : t_DavMethods
		- _defaultType : string
		- _errorPage : t_ErrorPages
		- _index : t_Index
		- _keepAliveTimeout : t_keepAliveTimeout
		- _allowedMethods : t_AllowedMethods
		- _root : string
		- _types : t_MimeTypes
		- _uri : string
		- _modifier : e_Modifier
		- _redirect : Return
		- _enableCGI : bool
		- _cgiExtensions : t_CgiExtensions
		--
		+ LocationConfig()
		+ {static} getLogger() : t_Logger
		+ getAutoindex() : bool
		+ setAutoindex(autoindex : bool) : void
		+ getClientMaxBodySize() : t_clientMaxBodySize
		+ setClientMaxBodySize(clientMaxBodySize : t_clientMaxBodySize) : void
		+ getDavPutPath() : string
		+ setDavPutPath(davPutPath : string) : void
		+ getDavAccess() : t_Perms
		+ setDavAccess(davAccess : t_Perms) : void
		+ getDavMethods() : t_DavMethods
		+ setDavMethods(davMethods : t_DavMethods) : void
		+ getDefaultType() : string
		+ setDefaultType(defaultType : string) : void
		+ getErrorPage() : t_ErrorPages
		+ setErrorPage(errorPage : t_ErrorPages) : void
		+ getIndex() : t_Index
		+ setIndex(index : t_Index) : void
		+ getKeepAliveTimeout() : t_keepAliveTimeout
		+ setKeepAliveTimeout(keepAliveTimeout : t_keepAliveTimeout) : void
		+ getAllowedMethods() : t_AllowedMethods
		+ setAllowedMethods(allowedMethods : t_AllowedMethods) : void
		+ getRoot() : string
		+ setRoot(root : string) : void
		+ getTypes() : t_MimeTypes
		+ setTypes(types : t_MimeTypes) : void
		+ getUri() : string
		+ setUri(uri : string) : void
		+ getModifier() : e_Modifier
		+ setModifier(modifier : e_Modifier) : void
		+ getRedirect() : Return
		+ setRedirect(redirect : Return) : void
		+ getEnableCGI() : bool
		+ setEnableCGI(enableCGI : bool) : void
		+ getCgiExtensions() : t_CgiExtensions
		+ setCgiExtensions(cgiExtensions : t_CgiExtensions) : void
	}
}

namespace webserv.cgi {


}

namespace webserv {

	class "HTTPServer" as HTTPServer <<singleton>> {
		- _logger : t_Logger
		- _defaultConfigPath : string
		- _parser : Parser
		- _httpConfig : HTTPConfig
		- _serverFactory : ServerFactory
		- _servers : t_Servers
		- _ioMultiplexer : t_ioMultiplexer
		- _clientHandler : ClientHandler
		- _headerRegistry : HTTPHeadersRegistry
		- _statusCodeRegistry : StatusCodeRegistry
		--
		- HTTPServer()
		- loadConfig() : void
		- connectClient(socket : t_SocketPairServer, serverConfig : ServerConfig) : void
  		+ {static} getInstance() : HTTPServer
  		+ {static} getLogger() : t_Logger
  		+ setup() : void
		+ run() : void
		+ setConfigPath(configPath : string) : void
		+ getHTTPConfig() : HTTPConfig
	}

	class "ServerFactory" as ServerFactory {
		- _logger : t_Logger
		- _httpConfig : HTTPConfig
		--
		+ ServerFactory()
		+ ServerFactory(httpConfig : HTTPConfig)
		+ {static} getLogger() : t_Logger
		+ createServers() : t_Servers
	}

	class "Server" as Server {
		- _logger : t_Logger
		- _config : ServerConfig
		- _sockets : t_ServerSockets
		--
		- createSockets() : void
		- setSocketOption(socket : common::core::net::TcpServer, listen : Listen, ai_family : int, addr : t_AddrPortPair) : void
		+ Server()
		+ Server(config : ServerConfig)
		+ {static} getLogger() : t_Logger
		+ getSockets() : t_ServerSockets
		+ getConfig() : ServerConfig
	}

	Client "1" *-- "1" ExecutionHandler
	Client "1" *-- "1" RequestHandler
	Client "1" *-- "1" ResponseHandler
	Client "1" *-- "1" HTTPError
	Client "1" *-- "1" ServerConfig
	Client ..> e_ClientStatus : uses

	ClientHandler "1" *-- "0..*" Client

	ErrorPage "1" *-- "1..*" StatusCode

	ExecutionHandler ..> e_ExecutionHandlerFlags : uses

	HTTPConfig "1" *-- "0..*" ErrorPage
	HTTPConfig "1" *-- "1..*" ServerConfig

	HTTPHeader ..> HTTPHeadersRegistry : uses

	HTTPServer "1" *-- "1" ClientHandler
	HTTPServer --> "1" HTTPHeadersRegistry : ref
	HTTPServer --> "1" HTTPConfig : ref
	HTTPServer "1" *-- "1" Parser
	HTTPServer "1" *-- "1..*" Server
	HTTPServer "1" *-- "1" ServerFactory
	HTTPServer --> "1" StatusCodeRegistry : ref

	LocationConfig "1" *-- "0..*" ErrorPage
	LocationConfig "1" *-- "0..1" Return
	LocationConfig ..> e_Method : uses
	LocationConfig ..> e_Modifier : uses

	Parser ..> Request : creates
	Parser ..> HTTPConfig : creates
	Parser ..> e_ParserFlags : uses

	ServerConfig "1" *-- "0..*" ErrorPage
	ServerConfig "1" *-- "1..*" Listen
	ServerConfig "1" *-- "0..*" LocationConfig

	ServerFactory ..> Server : creates
	ServerFactory ..> HTTPConfig : uses

	Server "1" --> "1" ServerConfig : configures

	StatusCode ..> StatusCodeRegistry : uses

	Request "1" *-- "1" LocationConfig
	Request ..> HTTPHeader : uses
	Request ..> e_RequestFlags : uses

	RequestHandler "1" *-- "1" Request
	RequestHandler "1" *-- "1" Parser
	RequestHandler --> ServerConfig : ref

	Response ..> HTTPHeader : uses
	Response ..> StatusCode : uses

	ResponseHandler "1" *-- "1" Response

	Return ..> StatusCode : uses
}

	webserv.client.Client "1" *-- "1" common.core.net.TcpClient

	webserv.handler.ClientHandler ..> common.core.io.IEventIO : uses

	webserv.parser.Parser ..> ABNF : uses

	webserv.HTTPServer "1" *-- "1" log42.logger.Logger
	webserv.HTTPServer "1" *-- "1" common.core.io.IEventIO

	webserv.Server "1" *-- "1..*" common.core.net.TcpServer

	webserv.handler.ExecutionHandler ..> common.core.utils.Directory : uses
	webserv.handler.ExecutionHandler ..> common.core.utils.DirectoryIterator : uses

	webserv.client.HTTPError --|> std.exception : inherits

note bottom of webserv
	**Types (webserv/types.hpp)**
	t_Logger           = common::core::raii::SharedPtr<log42::logger::Logger>
	t_ioMultiplexer    = common::core::raii::SharedPtr<common::core::io::IEventIO>
	t_Headers          = map<string, list<HTTPHeader>>
	t_HeadersRegistry  = map<string, HTTPHeader>
	t_StatusCodesRegistry = map<unsigned short, StatusCode>
	t_MimeTypes        = map<string, string>
	t_CgiExtensions    = map<string, string>
	t_DavMethods       = set<e_Method>
	t_AllowedMethods   = set<e_Method>
	t_ErrorPages       = vector<ErrorPage>
	t_ServerConfigs    = vector<ServerConfig>
	t_LocationConfigs  = vector<LocationConfig>
	t_Listen           = vector<Listen>
	t_Servernames      = vector<string>
	t_Index            = vector<string>
	t_StatusCodes      = vector<StatusCode>
	t_Servers          = vector<Server>
	t_Clients          = map<int, Client>
	t_raw              = vector<unsigned char>
	t_SubRules         = vector<string>
	t_clientMaxBodySize = unsigned int
	t_keepAliveTimeout = unsigned int
	t_Perms            = unsigned short
	t_SocketPairServer = pair<common::core::net::TcpServer, sockaddr_storage>
	t_SocketPairClient = pair<common::core::net::TcpClient, sockaddr_storage>
	t_ServerSockets    = vector<t_SocketPairServer>
	t_AddrPortPair     = pair<string, string>
end note

@enduml
